version: "3.7"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
            - './src:/home/node/app/src'
            - './nodemon.json:/home/node/app/nodemon.json'
            - './package.json:/home/node/app/package.json'
        ports:
            - '8080:8080'
        command: npm run dev
